# Generated by Django 4.1.3 on 2022-11-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_tokenmodel_used_remove_tokenmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='phone',
        ),
        migrations.AddField(
            model_name='tokenmodel',
            name='phone',
            field=models.CharField(default='exit', max_length=12),
            preserve_default=False,
        ),
    ]
