# Generated by Django 4.1.3 on 2022-12-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profilemodel_phone_tokenmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(choices=[(1, 'Eco Activist'), (2, 'Guide'), (3, 'Partner')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(upload_to='profiles'),
        ),
    ]
