# Generated by Django 4.1.3 on 2022-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profilemodel_role_alter_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='role',
            field=models.CharField(choices=[('1', 'Eco Activist'), ('2', 'Guide'), ('3', 'Partner')], max_length=20),
        ),
    ]
