# Generated by Django 4.1.3 on 2022-12-09 10:09

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(upload_to='violations')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViolationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('title', models.CharField(choices=[('1', 'Illegal Dump'), ('2', 'Deforestation'), ('3', 'Water Pollution')], max_length=20)),
                ('comment', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='violationmodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='events_viol_created_bdfdcf_brin'),
        ),
        migrations.AddField(
            model_name='violationimagemodel',
            name='violation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.violationmodel'),
        ),
        migrations.AddIndex(
            model_name='violationimagemodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='events_viol_created_6ecab6_brin'),
        ),
    ]
