# Generated by Django 4.1.3 on 2022-12-24 12:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_recyclemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclemodel',
            name='recycle_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Scrap metal'), (2, 'Waste paper'), (3, 'Glass'), (4, 'Mechanism'), (5, 'Furniture'), (6, 'Plastic')], max_length=20),
        ),
        migrations.AlterField(
            model_name='recyclemodel',
            name='working_days',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=20),
        ),
    ]
