# Generated by Django 4.1.3 on 2022-12-29 15:08

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_alter_recyclemodel_recycle_types_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargingStationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('geocode', models.TextField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('payment_method', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Plastic card'), (2, 'Cash'), (3, 'App')], max_length=20)),
                ('charging_type', models.CharField(choices=[(1, 'Slow'), (1, 'Fast'), (1, 'Rapid'), (1, 'Extra Fast')], max_length=20)),
                ('description', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargingStationImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('image', models.ImageField(upload_to='charging stations')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='events.chargingstationmodel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='chargingstationmodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='events_char_created_51dc57_brin'),
        ),
        migrations.AddIndex(
            model_name='chargingstationimagemodel',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at', 'updated_at'], name='events_char_created_905bc6_brin'),
        ),
    ]
